# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eec988afd4f3686c9a75506ac4331a524856c414f0d48abffa28d89535ad5ac84c24a3153ae589833131a43106a0dfb0d6e0b9264637e92ecdcdb0eeb58efd3

test:
  secret_key_base: 054177650461c7cededae9b5cc1e917ed02babf3369ce2ae10827f2c3e42d01b142a9b6d204f9cb8032c99ffff7a01de85973ecadabb5af63de8bda31175d41e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
